# Generated by Django 2.2.4 on 2019-08-13 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=30)),
                ('ip_address', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('browser', models.CharField(max_length=30)),
                ('screen_resolution', models.CharField(max_length=30)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
