# Generated by Django 2.2.4 on 2019-08-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190816_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
